version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: eipr/api:latest
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-local}
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@db:5432/eipr}
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL:-postgresql://postgres:postgres@db:5432/eipr}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      SMTP_HOST: ${SMTP_HOST:-mailhog}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-no-reply@eipr.local}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      STRIPE_TERMINAL_LOCATION: ${STRIPE_TERMINAL_LOCATION:-}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-}
      TWILIO_MESSAGING_SERVICE_SID: ${TWILIO_MESSAGING_SERVICE_SID:-}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-http://minio:9000}
      S3_BUCKET: ${S3_BUCKET:-eipr}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-minioadmin}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-minioadmin}
      QBO_EXPORT_DIR: ${QBO_EXPORT_DIR:-/app/exports}
      KISI_API_KEY: ${KISI_API_KEY:-}
      KISI_DOOR_ID: ${KISI_DOOR_ID:-}
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - mailhog
      - minio
      - createbuckets
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eipr
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
  minio:
    image: minio/minio:RELEASE.2024-08-29T01-40-52Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-minioadmin}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  createbuckets:
    image: minio/mc:RELEASE.2024-08-20T16-00-19Z
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command: >-
      until /usr/bin/mc alias set minio http://minio:9000 ${S3_ACCESS_KEY_ID:-minioadmin} ${S3_SECRET_ACCESS_KEY:-minioadmin}; do sleep 1; done &&
      /usr/bin/mc mb minio/${S3_BUCKET:-eipr} || true
    restart: "no"

volumes:
  pgdata:
  minio-data:
