import React, { useEffect } from "react";
import "./print.css";

type MetaItem = {
  label: string;
  value?: string | number | null;
};

type PrintLayoutProps = {
  title: string;
  meta?: MetaItem[];
  autoPrint?: boolean;
  children: React.ReactNode;
};

const FACILITY_NAME = (import.meta.env.VITE_FACILITY_NAME as string) || "Eastern Iowa Pet Resort";

export default function PrintLayout({ title, meta, autoPrint = true, children }: PrintLayoutProps) {
  useEffect(() => {
    document.body.classList.add("print-mode");
    let handle: number | undefined;
    if (autoPrint) {
      handle = window.setTimeout(() => window.print(), 150);
    }
    return () => {
      document.body.classList.remove("print-mode");
      if (handle) {
        window.clearTimeout(handle);
      }
    };
  }, [autoPrint]);

  return (
    <div className="print-container">
      <header className="print-header" aria-label="Document heading">
        <div>
          <div className="print-title">{title}</div>
          <div className="print-meta" aria-label="Facility">
            <span>{FACILITY_NAME}</span>
          </div>
        </div>
        <div className="print-meta" aria-label="Document details">
          <span>{new Date().toLocaleString()}</span>
          {meta?.map((item) => (
            <span key={item.label}>
              <strong>{item.label}:</strong>
              {" "}
              {item.value ?? "—"}
            </span>
          ))}
        </div>
      </header>
      <main>{children}</main>
      <footer className="print-footer" aria-label="Document footer">
        Generated by EIPR Portal • {FACILITY_NAME}
      </footer>
    </div>
  );
}
