name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eipr
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Ruff lint
        working-directory: backend
        run: ruff check app tests

      - name: Ruff format check
        working-directory: backend
        run: ruff format --check app tests

      - name: Mypy
        working-directory: backend
        run: mypy app tests

      - name: Pytest with coverage
        working-directory: backend
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/eipr
          SYNC_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eipr
          JWT_SECRET_KEY: test-secret
          JWT_ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
        run: pytest --cov=app/models --cov=app/schemas --cov-report=term --cov-report=xml --cov-fail-under=85
